title: Shortcuts
description: a short collection of useful shortcuts

theme: minima

# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://shortcuts.billiem.uk" # the base hostname & protocol for your site, e.g. http://example.com
